name: hello_world
description: An app built using Flutter for web

environment:
  sdk: '>=2.4.0 <3.0.0'
  flutter: ^1.12.13

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0+1
